### ISSUE TITLE
Connect Login Server to Database (3 - BE, DB)

### ISSUE THREAD

**Issue by HarounAlarabi** [malkitbenning/teachers-pet#43]
Outcome:
Show summary page of pupils on a successful login
If unsuccessful - invalid username or password message, try again

To Do:

1. Install dotenv
2. Move validate user function to a separate module file
3. Create a DB query to validate username and password
4. Pass teacher id as a router state variable
5. Test

Dev Notes:
https://www.youtube.com/watch?v=xc7UduoAh-0

**Comment by m4ndycheung** [comment]
For testing:
Username: Peter
Password: password
